/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframes;



import hr_management_system.Recruitment;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ABS
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }
    // display stuff from database
    Connector c = new Connector();
    public int getdata(String query){
        
        
        c.runSelect(query);
        int rowCount = 0;
        try {
            if(c.rs.next()){
                try{
                    rowCount = c.rs.getInt(1);
                }catch(Exception e){}}
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return rowCount;
    
    }
    
    public void displaydata(){
        String query1 = "SELECT COUNT(*) FROM emp_info"  ;
        labelemp.setText(Integer.toString(getdata(query1)));
        
        String event = "SELECT COUNT(*) FROM Event"  ;
        labelevent.setText(Integer.toString(getdata(event)));
        
        String project = "SELECT COUNT(*) FROM Project"  ;
        labelproject.setText(Integer.toString(getdata(project)));
        
        String rec = "SELECT COUNT(*) FROM Recruitment"  ;
        labelrec.setText(Integer.toString(getdata(rec)));
        
        String sel = "SELECT COUNT(*) FROM Selection"  ;
        labelselect.setText(Integer.toString(getdata(sel)));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Panelblack = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        home1 = new javax.swing.JPanel();
        home10 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        home = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        home2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        home3 = new javax.swing.JPanel();
        ManageEmployee = new javax.swing.JLabel();
        home5 = new javax.swing.JPanel();
        report = new javax.swing.JLabel();
        home6 = new javax.swing.JPanel();
        ManageEvents = new javax.swing.JLabel();
        home7 = new javax.swing.JPanel();
        ManageProject = new javax.swing.JLabel();
        home8 = new javax.swing.JPanel();
        leave = new javax.swing.JLabel();
        home9 = new javax.swing.JPanel();
        Recruitment = new javax.swing.JLabel();
        home11 = new javax.swing.JPanel();
        Selection = new javax.swing.JLabel();
        homescreen = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        labelrec = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelemp = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelevent = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        labelproject = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        labelselect = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_emp = new rojeru_san.complementos.RSTableMetro();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_project = new rojeru_san.complementos.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(102, 102, 255));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_menu_48px_1.png"))); // NOI18N
        header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Panelblack.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout PanelblackLayout = new javax.swing.GroupLayout(Panelblack);
        Panelblack.setLayout(PanelblackLayout);
        PanelblackLayout.setHorizontalGroup(
            PanelblackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        PanelblackLayout.setVerticalGroup(
            PanelblackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        header.add(Panelblack, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 5, 50));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1850, 0, 40, 60));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Human Resource Management System");
        header.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, 40));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/male_user_50px.png"))); // NOI18N
        jLabel4.setText("Welcome , Admin");
        header.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 0, 230, 60));

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1900, 70));

        sidebar.setBackground(new java.awt.Color(51, 51, 51));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home1.setBackground(new java.awt.Color(51, 51, 51));
        home1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home10.setBackground(new java.awt.Color(102, 102, 255));
        home10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Exit_26px_2.png"))); // NOI18N
        jLabel16.setText("Logout");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        home10.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 270, 40));

        home1.add(home10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 60));

        sidebar.add(home1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 730, 340, 60));

        home.setBackground(new java.awt.Color(255, 51, 51));
        home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel5.setText("     Home Page");
        home.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 220, 40));

        sidebar.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 340, 60));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Features");
        sidebar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 270, 40));

        home2.setBackground(new java.awt.Color(51, 51, 51));
        home2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Library_26px_1.png"))); // NOI18N
        jLabel8.setText("     Dashboard");
        home2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 270, 40));

        sidebar.add(home2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 340, 60));

        home3.setBackground(new java.awt.Color(51, 51, 51));
        home3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManageEmployee.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        ManageEmployee.setForeground(new java.awt.Color(153, 153, 153));
        ManageEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_People_50px.png"))); // NOI18N
        ManageEmployee.setText("Manage Employees");
        ManageEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageEmployeeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ManageEmployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ManageEmployeeMouseExited(evt);
            }
        });
        home3.add(ManageEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 270, 40));

        sidebar.add(home3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 340, 60));

        home5.setBackground(new java.awt.Color(51, 51, 51));
        home5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        report.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        report.setForeground(new java.awt.Color(153, 153, 153));
        report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_People_50px.png"))); // NOI18N
        report.setText("Report Employees");
        report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportMouseClicked(evt);
            }
        });
        home5.add(report, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 270, 50));

        sidebar.add(home5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 340, 60));

        home6.setBackground(new java.awt.Color(51, 51, 51));
        home6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManageEvents.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        ManageEvents.setForeground(new java.awt.Color(153, 153, 153));
        ManageEvents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Sell_26px.png"))); // NOI18N
        ManageEvents.setText("   Manage Events");
        ManageEvents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageEventsMouseClicked(evt);
            }
        });
        home6.add(ManageEvents, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 270, 40));

        sidebar.add(home6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 340, 60));

        home7.setBackground(new java.awt.Color(51, 51, 51));
        home7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManageProject.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        ManageProject.setForeground(new java.awt.Color(153, 153, 153));
        ManageProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Books_26px.png"))); // NOI18N
        ManageProject.setText("   Manage Projects");
        ManageProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageProjectMouseClicked(evt);
            }
        });
        home7.add(ManageProject, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 270, 40));

        sidebar.add(home7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 340, 60));

        home8.setBackground(new java.awt.Color(51, 51, 51));
        home8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leave.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        leave.setForeground(new java.awt.Color(153, 153, 153));
        leave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_Shelf_50px.png"))); // NOI18N
        leave.setText("Manage Leaves");
        leave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leaveMouseClicked(evt);
            }
        });
        home8.add(leave, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 270, 40));

        sidebar.add(home8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 340, 60));

        home9.setBackground(new java.awt.Color(51, 51, 51));
        home9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Recruitment.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        Recruitment.setForeground(new java.awt.Color(153, 153, 153));
        Recruitment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_People_50px.png"))); // NOI18N
        Recruitment.setText("Reqruitment System");
        Recruitment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RecruitmentMouseClicked(evt);
            }
        });
        home9.add(Recruitment, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 270, 40));

        sidebar.add(home9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 340, 60));

        home11.setBackground(new java.awt.Color(51, 51, 51));
        home11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Selection.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        Selection.setForeground(new java.awt.Color(153, 153, 153));
        Selection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Read_Online_26px.png"))); // NOI18N
        Selection.setText("   Selection System");
        Selection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SelectionMouseClicked(evt);
            }
        });
        home11.add(Selection, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 270, 40));

        sidebar.add(home11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 340, 60));

        getContentPane().add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 340, 960));

        homescreen.setBackground(new java.awt.Color(255, 255, 255));
        homescreen.setForeground(new java.awt.Color(255, 255, 255));
        homescreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 1, 1, 1, new java.awt.Color(102, 102, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelrec.setFont(new java.awt.Font("Segoe UI Black", 1, 50)); // NOI18N
        labelrec.setForeground(new java.awt.Color(102, 102, 102));
        labelrec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_People_50px.png"))); // NOI18N
        labelrec.setText("10");
        jPanel1.add(labelrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 140, -1));

        homescreen.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 260, 140));

        jLabel18.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Employee Details");
        homescreen.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 250, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("No of Employees");
        homescreen.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 180, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelemp.setFont(new java.awt.Font("Segoe UI Black", 1, 50)); // NOI18N
        labelemp.setForeground(new java.awt.Color(102, 102, 102));
        labelemp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_People_50px.png"))); // NOI18N
        labelemp.setText("10");
        jPanel2.add(labelemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 140, -1));

        homescreen.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 260, 140));

        jLabel21.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Events");
        homescreen.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 180, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelevent.setFont(new java.awt.Font("Segoe UI Black", 1, 50)); // NOI18N
        labelevent.setForeground(new java.awt.Color(102, 102, 102));
        labelevent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_Shelf_50px.png"))); // NOI18N
        labelevent.setText("10");
        jPanel3.add(labelevent, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 140, -1));

        homescreen.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 260, 140));

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelproject.setFont(new java.awt.Font("Segoe UI Black", 1, 50)); // NOI18N
        labelproject.setForeground(new java.awt.Color(102, 102, 102));
        labelproject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Sell_26px.png"))); // NOI18N
        labelproject.setText(" 10");
        jPanel4.add(labelproject, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 170, -1));

        homescreen.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 260, 140));

        jLabel25.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("Selected Candidates ");
        homescreen.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 230, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 1, 1, 1, new java.awt.Color(102, 102, 255)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelselect.setFont(new java.awt.Font("Segoe UI Black", 1, 50)); // NOI18N
        labelselect.setForeground(new java.awt.Color(102, 102, 102));
        labelselect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_People_50px.png"))); // NOI18N
        labelselect.setText(" 10");
        jPanel5.add(labelselect, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 170, -1));

        homescreen.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 260, 140));

        jLabel23.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("Active Projects");
        homescreen.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 180, -1));

        Table_emp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", "abs", "cheif", "20", "20", "not reported"},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "Name", "Designation", "Salary", "Age", "Report Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_emp.setColorBackgoundHead(new java.awt.Color(102, 102, 255));
        Table_emp.setColorBordeFilas(new java.awt.Color(102, 102, 255));
        Table_emp.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        Table_emp.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 25)); // NOI18N
        Table_emp.setFuenteFilas(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        Table_emp.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        Table_emp.setFuenteHead(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        Table_emp.setRowHeight(40);
        Table_emp.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Table_emp);
        if (Table_emp.getColumnModel().getColumnCount() > 0) {
            Table_emp.getColumnModel().getColumn(0).setResizable(false);
            Table_emp.getColumnModel().getColumn(1).setResizable(false);
            Table_emp.getColumnModel().getColumn(2).setResizable(false);
            Table_emp.getColumnModel().getColumn(3).setResizable(false);
            Table_emp.getColumnModel().getColumn(4).setResizable(false);
        }

        homescreen.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 880, 360));

        jLabel27.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("Recruitment Applicants");
        homescreen.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 250, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("Project Details");
        homescreen.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, 250, -1));

        Table_project.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "01", "abs", "cheif", "20"},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Deadline", "Project Manager", "Department"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_project.setColorBackgoundHead(new java.awt.Color(102, 102, 255));
        Table_project.setColorBordeFilas(new java.awt.Color(102, 102, 255));
        Table_project.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        Table_project.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 25)); // NOI18N
        Table_project.setFuenteFilas(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        Table_project.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        Table_project.setFuenteHead(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        Table_project.setRowHeight(40);
        Table_project.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(Table_project);
        if (Table_project.getColumnModel().getColumnCount() > 0) {
            Table_project.getColumnModel().getColumn(0).setResizable(false);
            Table_project.getColumnModel().getColumn(1).setResizable(false);
            Table_project.getColumnModel().getColumn(2).setResizable(false);
            Table_project.getColumnModel().getColumn(3).setResizable(false);
            Table_project.getColumnModel().getColumn(4).setResizable(false);
        }

        homescreen.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 880, 360));

        getContentPane().add(homescreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 1570, 950));

        setSize(new java.awt.Dimension(1905, 1023));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //initiate the boxes
        displaydata();
        
        // initiate tables
            try {
    Connector c = new Connector();

    // Run the select query
    c.runSelect("select * from emp_info");

    // Get the metadata (column count)
    int col = c.rs.getMetaData().getColumnCount();

    // Create an empty String array to store row data
    ArrayList<String[]> rowData = new ArrayList<>();

    // Loop through each row in the result set
    while (c.rs.next()) {
      String[] row = new String[col];
      for (int i = 0; i < col; i++) {
        row[i] = c.rs.getString(i + 1); // Get data starting from column 1 (index 0)
      }
      rowData.add(row); // Add the current row to the list
    }

    // Convert the list to a 2D String array
    String[][] dataArray = new String[rowData.size()][col];
    for (int i = 0; i < rowData.size(); i++) {
      dataArray[i] = rowData.get(i);
    }

    String[] columnName = {"Employee ID", "Name", "Designation", "Salary","Age","Report Status"};
    DefaultTableModel model = (DefaultTableModel) Table_emp.getModel();
    model.setDataVector(dataArray, columnName);

  } catch (SQLException e) {
    e.printStackTrace();
  }
        // for project Table    
    try {
    Connector c = new Connector();

    // Run the select query
    c.runSelect("select * from Project");

    // Get the metadata (column count)
    int col = c.rs.getMetaData().getColumnCount();

    // Create an empty String array to store row data
    ArrayList<String[]> rowData = new ArrayList<>();

    // Loop through each row in the result set
    while (c.rs.next()) {
      String[] row = new String[col];
      for (int i = 0; i < col; i++) {
        row[i] = c.rs.getString(i + 1); // Get data starting from column 1 (index 0)
      }
      rowData.add(row); // Add the current row to the list
    }

    // Convert the list to a 2D String array
    String[][] dataArray = new String[rowData.size()][col];
    for (int i = 0; i < rowData.size(); i++) {
      dataArray[i] = rowData.get(i);
    }

    String[] columnName = {"ID","Name" ,"Deadline", "Project Manager"};
    DefaultTableModel model = (DefaultTableModel) Table_project.getModel();
    model.setDataVector(dataArray, columnName);

  } catch (SQLException e) {
    e.printStackTrace();
  } 
    
    

    }//GEN-LAST:event_formWindowOpened

    private void ManageEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageEmployeeMouseClicked
        // TODO add your handling code here:
        ManageEmployee employee= new ManageEmployee();
        employee.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_ManageEmployeeMouseClicked

    private void ManageProjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageProjectMouseClicked
        // TODO add your handling code here:
        ProjectForm prop = new ProjectForm();
        prop.setVisible(true);
        dispose();
    }//GEN-LAST:event_ManageProjectMouseClicked

    private void reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportMouseClicked
        // TODO add your handling code here:
        ReportForm form= new ReportForm();
        form.setVisible(true);
        dispose();
    }//GEN-LAST:event_reportMouseClicked

    private void leaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leaveMouseClicked
        // TODO add your handling code here:
        LeaveForm form = new LeaveForm();
        form.setVisible(true);
        dispose ();
    }//GEN-LAST:event_leaveMouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        LoginForm form = new LoginForm();
        form.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void ManageEventsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageEventsMouseClicked
        // TODO add your handling code here:
        Event form = new Event();
        form.setVisible(true);
        dispose();
    }//GEN-LAST:event_ManageEventsMouseClicked

    private void RecruitmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecruitmentMouseClicked
        // TODO add your handling code here:
        Recruitment_form form = new Recruitment_form();
        form.setVisible(true);
        dispose();
    }//GEN-LAST:event_RecruitmentMouseClicked

    private void SelectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelectionMouseClicked
        // TODO add your handling code here:
        Selectionform form = new Selectionform();
        form.setVisible(true);
        dispose();
    }//GEN-LAST:event_SelectionMouseClicked

    private void ManageEmployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageEmployeeMouseEntered
        // TODO add your handling code here:
        ManageEmployee.setBackground(Color.black);
    }//GEN-LAST:event_ManageEmployeeMouseEntered

    private void ManageEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageEmployeeMouseExited
        // TODO add your handling code here:
        ManageEmployee.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_ManageEmployeeMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ManageEmployee;
    private javax.swing.JLabel ManageEvents;
    private javax.swing.JLabel ManageProject;
    private javax.swing.JPanel Panelblack;
    private javax.swing.JLabel Recruitment;
    private javax.swing.JLabel Selection;
    private rojeru_san.complementos.RSTableMetro Table_emp;
    private rojeru_san.complementos.RSTableMetro Table_project;
    private javax.swing.JPanel header;
    private javax.swing.JPanel home;
    private javax.swing.JPanel home1;
    private javax.swing.JPanel home10;
    private javax.swing.JPanel home11;
    private javax.swing.JPanel home2;
    private javax.swing.JPanel home3;
    private javax.swing.JPanel home5;
    private javax.swing.JPanel home6;
    private javax.swing.JPanel home7;
    private javax.swing.JPanel home8;
    private javax.swing.JPanel home9;
    private javax.swing.JPanel homescreen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelemp;
    private javax.swing.JLabel labelevent;
    private javax.swing.JLabel labelproject;
    private javax.swing.JLabel labelrec;
    private javax.swing.JLabel labelselect;
    private javax.swing.JLabel leave;
    private javax.swing.JLabel report;
    private javax.swing.JPanel sidebar;
    // End of variables declaration//GEN-END:variables
}
